[known]
docker-host ansible_host=192.168.2.13 ansible_user=bart ansible_ssh_private_key_file=~/.ssh/id_ed25519
scripts ansible_host=192.168.2.14 ansible_user=bart ansible_ssh_private_key_file=~/.ssh/id_ed25519
frigate ansible_host=192.168.2.11 ansible_user=bart ansible_ssh_private_key_file=~/.ssh/id_ed25519
proxmox ansible_host=192.168.2.132 ansible_user=bart ansible_ssh_private_key_file=~/.ssh/id_ed25519

[known:vars]
ansible_ssh_common_args=-F /dev/null
