---
managed_groups:
  - name: admin
    system: false

managed_users:
  - name: bart
    comment: Bart
    groups:
      - sudo
      - admin
    shell: /bin/bash
    create_home: true
    state: present
    authorized_keys:
      - file: ansible_management.pub

  - name: hermes
    comment: hermes-agent
    groups:
      - sudo
      - admin
    shell: /bin/bash
    create_home: true
    state: present
    authorized_keys:
      - file: ansible_management.pub
      - file: hermes_agent.pub
      
       