[web]
web01 ansible_host=192.168.2.101 ansible_user=bart
web02 ansible_host=192.168.2.102 ansible_user=bart

[docker]
docker01 ansible_host=192.168.2.111 ansible_user=bart
docker02 ansible_host=192.168.2.112 ansible_user=bart

[base:children]
web
docker

[users_ssh:children]
web
docker

[node_exporter:children]
web
docker

[updates:children]
web
docker
