---
- name: Installeer basispackages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: Stel timezone in
  community.general.timezone:
    name: "{{ timezone }}"
